export function DemoFippaCard() {
  return (
    <div
      className="mx-auto max-w-lg overflow-hidden rounded-xl light-scope"
      style={{
        background: '#FAFAF9',
        boxShadow: '0 0 80px rgba(250,250,249,0.18), 0 24px 60px rgba(20,18,14,0.35)',
      }}
      data-scroll-fade
      aria-label="Example FOI request generated by Open Cave"
    >
      <div className="flex items-center justify-between border-b border-border px-6 py-3.5">
        <span
          className="text-[11px] uppercase tracking-[0.14em] text-text-faint"
          style={{ fontFamily: 'var(--font-mono)' }}
        >
          Freedom of Information Request
        </span>
        <span
          className="rounded-full px-2.5 py-0.5 text-[11px] font-semibold"
          style={{
            background: 'color-mix(in srgb, var(--accent-lever) 9%, transparent)',
            color: 'var(--accent-lever)',
            fontFamily: 'var(--font-body)',
          }}
        >
          Ready to file
        </span>
      </div>

      <div className="border-t border-border px-6 py-5">
        <div className="space-y-3" style={{ lineHeight: 1.6 }}>
          <p
            className="text-text-secondary"
            style={{ fontFamily: 'var(--font-mono)', fontSize: '12px' }}
          >
            <span className="text-text-muted">To:</span> District Manager,
            Chilliwack Natural Resource District, Ministry of Forests
          </p>
          <p
            className="text-text-secondary"
            style={{ fontFamily: 'var(--font-mono)', fontSize: '12px' }}
          >
            <span className="text-text-muted">Re:</span> Cutting Permit
            Application CP-2024-0312 under FSP #847, Block CH-4417
          </p>
          <p
            className="pt-2 text-text-primary"
            style={{ fontFamily: 'var(--font-serif)', fontSize: 15.5 }}
          >
            Pursuant to the Freedom of Information and Protection of Privacy Act
            (RSBC 1996, c.165), I request access to the following records:
          </p>
          <ol
            className="list-decimal space-y-1.5 pl-5 text-text-primary"
            style={{ fontFamily: 'var(--font-serif)', fontSize: 15 }}
          >
            <li>
              All correspondence between district staff and the licensee
              regarding the cutting permit application, from January 2023 to
              present
            </li>
            <li>
              The complete Watershed Assessment (Appendix D) referenced in
              Forest Stewardship Plan #847, including all supporting
              hydrological data
            </li>
            <li>
              Visual Quality Assessment field notes, photographs, and any
              simulation renderings prepared for Block CH-4417
            </li>
          </ol>
        </div>
      </div>
    </div>
  )
}
