export function DemoFippaCard() {
  return (
    <div
      className="mx-auto max-w-lg overflow-hidden rounded-xl border border-border-strong bg-surface-1 shadow-sm"
      data-scroll-fade
      aria-label="Example FOI request generated by Open Cave"
    >
      <div className="px-6 py-3" style={{ borderTop: '3px solid #DC2626' }}>
        <div className="flex items-center justify-between">
          <span
            className="text-xs font-semibold uppercase tracking-wider text-text-muted"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Freedom of Information Request
          </span>
          <span className="rounded-full bg-surface-2 px-2.5 py-0.5 text-[10px] font-medium text-text-secondary">
            Ready to File
          </span>
        </div>
      </div>

      <div className="border-t border-border px-6 py-5">
        <div
          className="space-y-3 text-text-secondary"
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '12px',
            lineHeight: 1.6,
          }}
        >
          <p>
            <span className="text-text-muted">To:</span> District Manager,
            Chilliwack Natural Resource District, Ministry of Forests
          </p>
          <p>
            <span className="text-text-muted">Re:</span> Cutting Permit
            Application CP-2024-0312 under FSP #847, Block CH-4417
          </p>
          <p className="pt-2">
            Pursuant to the Freedom of Information and Protection of Privacy Act
            (RSBC 1996, c.165), I request access to the following records:
          </p>
          <ol className="list-decimal space-y-1.5 pl-5">
            <li>
              All correspondence between district staff and the licensee
              regarding the cutting permit application, from January 2023 to
              present
            </li>
            <li>
              The complete Watershed Assessment (Appendix D) referenced in
              Forest Stewardship Plan #847, including all supporting
              hydrological data
            </li>
            <li>
              Visual Quality Assessment field notes, photographs, and any
              simulation renderings prepared for Block CH-4417
            </li>
          </ol>
        </div>
      </div>
    </div>
  )
}
