-- Baseline schema migration — generated by drizzle-kit from src/lib/db/schema.ts
-- Generated: 2026-06-20
--
-- PURPOSE: Enables fresh-deploy reproducibility. Run this on a brand-new
-- empty database to create the full schema from scratch.
--
-- PROD APPLY STRATEGY:
--   Prod already has every object (the DB was built with drizzle-kit push).
--   DO NOT run this against prod directly — CREATE TYPE / CREATE TABLE will
--   error on existing objects (drizzle-kit does not emit IF NOT EXISTS here).
--   To record this migration as already-applied on prod, seed the journal
--   hash into Supabase's drizzle migration table once drizzle migrate is
--   wired up, or simply treat this as documentation + fresh-DB bootstrap only.
--
-- FOLLOW-ON MIGRATIONS (apply in order after this one on fresh DBs):
--   drizzle/migrations/0001_enable_rls.sql     -- RLS policies
--   drizzle/migrations/0002_vector_extension_hnsw_indexes.sql -- pgvector + HNSW

CREATE TYPE "public"."archive_access_type" AS ENUM('ipfs_gateway', 'arweave_direct', 'republic_app');--> statement-breakpoint
CREATE TYPE "public"."archive_status" AS ENUM('pending', 'ipfs_pinned', 'arweave_permanent', 'failed');--> statement-breakpoint
CREATE TYPE "public"."campaign_material_format" AS ENUM('json', 'markdown', 'html');--> statement-breakpoint
CREATE TYPE "public"."campaign_material_status" AS ENUM('draft', 'final');--> statement-breakpoint
CREATE TYPE "public"."campaign_material_type" AS ENUM('infographic', 'fact_sheet', 'social_post', 'talking_points', 'coalition_template', 'timeline', 'comparison');--> statement-breakpoint
CREATE TYPE "public"."credential_source" AS ENUM('investigation', 'peer_review', 'forum_post', 'campaign_material', 'lever_action', 'outcome', 'archive_record');--> statement-breakpoint
CREATE TYPE "public"."credential_type" AS ENUM('investigation_completed', 'foi_filed', 'foi_response_shared', 'campaign_used', 'outcome_tracked', 'forum_contribution', 'peer_review', 'jurisdiction_contributed', 'code_contributed', 'bug_report', 'translation', 'investigation_archived');--> statement-breakpoint
CREATE TYPE "public"."cross_reference_type" AS ENUM('cites', 'contradicts', 'amends', 'supersedes', 'references');--> statement-breakpoint
CREATE TYPE "public"."document_change_type" AS ENUM('content_changed', 'metadata_changed', 'deleted', 'retracted');--> statement-breakpoint
CREATE TYPE "public"."document_status" AS ENUM('processing', 'ready', 'failed');--> statement-breakpoint
CREATE TYPE "public"."document_type" AS ENUM('zoning_bylaw', 'budget', 'council_minutes', 'environmental_assessment', 'policy', 'foi_response', 'lobbyist_registration', 'campaign_finance', 'other', 'environmental_impact_statement', 'environmental_assessment_report', 'scoping_document', 'record_of_decision', 'biological_opinion', 'habitat_assessment');--> statement-breakpoint
CREATE TYPE "public"."gadfly_mode" AS ENUM('socratic', 'direct');--> statement-breakpoint
CREATE TYPE "public"."gadfly_question_type" AS ENUM('clarifying', 'probing', 'challenging', 'connecting', 'action');--> statement-breakpoint
CREATE TYPE "public"."gadfly_role" AS ENUM('gadfly', 'citizen');--> statement-breakpoint
CREATE TYPE "public"."gadfly_status" AS ENUM('active', 'completed', 'abandoned');--> statement-breakpoint
CREATE TYPE "public"."investigation_player_role" AS ENUM('beneficiary', 'decision_maker', 'affected', 'proponent', 'regulator', 'rights_holder', 'title_holder');--> statement-breakpoint
CREATE TYPE "public"."investigation_status" AS ENUM('active', 'archived');--> statement-breakpoint
CREATE TYPE "public"."issue_event_type" AS ENUM('deadline', 'meeting', 'decision', 'comment_period', 'custom');--> statement-breakpoint
CREATE TYPE "public"."issue_status" AS ENUM('upcoming', 'passed', 'completed');--> statement-breakpoint
CREATE TYPE "public"."lever_action_type" AS ENUM('fippa_request', 'public_comment', 'policy_brief', 'legal_template', 'media_spec', 'talking_points', 'coalition_template', 'mp_letter');--> statement-breakpoint
CREATE TYPE "public"."lever_status" AS ENUM('draft', 'final', 'filed');--> statement-breakpoint
CREATE TYPE "public"."moderation_action_type" AS ENUM('hide_post', 'unhide_post', 'lock_thread', 'unlock_thread', 'dismiss_report', 'appeal');--> statement-breakpoint
CREATE TYPE "public"."mp_ballot" AS ENUM('yes', 'no', 'paired', 'didnt_vote');--> statement-breakpoint
CREATE TYPE "public"."municipal_type" AS ENUM('city', 'district', 'regional_district', 'township', 'village', 'province', 'federal');--> statement-breakpoint
CREATE TYPE "public"."outcome_type" AS ENUM('fippa_response_received', 'comment_submitted', 'council_presentation', 'media_coverage', 'policy_change', 'assessment_decision', 'other');--> statement-breakpoint
CREATE TYPE "public"."player_type" AS ENUM('company', 'official', 'agency', 'organization', 'rights_holder');--> statement-breakpoint
CREATE TYPE "public"."policy_area" AS ENUM('zoning', 'housing', 'transit', 'budget_transparency', 'environment', 'foi_transparency', 'procurement', 'other', 'conservation', 'extraction', 'land_use', 'water_rights');--> statement-breakpoint
CREATE TYPE "public"."post_status" AS ENUM('visible', 'hidden', 'removed_by_author');--> statement-breakpoint
CREATE TYPE "public"."proposal_status" AS ENUM('draft', 'active', 'passed', 'rejected', 'executed');--> statement-breakpoint
CREATE TYPE "public"."proposal_type" AS ENUM('policy', 'feature', 'constitutional', 'funding');--> statement-breakpoint
CREATE TYPE "public"."regulatory_framework" AS ENUM('bc_eao', 'iaa', 'nepa', 'provincial_ea', 'other');--> statement-breakpoint
CREATE TYPE "public"."report_reason" AS ENUM('spam', 'harassment', 'misinformation', 'off_topic', 'other');--> statement-breakpoint
CREATE TYPE "public"."report_status" AS ENUM('pending', 'reviewed', 'dismissed', 'actioned');--> statement-breakpoint
CREATE TYPE "public"."report_target_type" AS ENUM('thread', 'post');--> statement-breakpoint
CREATE TYPE "public"."shadow_alert_type" AS ENUM('missing_topic', 'missing_entity', 'missing_jurisdiction_pattern');--> statement-breakpoint
CREATE TYPE "public"."thread_status" AS ENUM('open', 'locked', 'archived');--> statement-breakpoint
CREATE TYPE "public"."vote_choice" AS ENUM('for', 'against', 'abstain');--> statement-breakpoint
CREATE TYPE "public"."vote_result" AS ENUM('passed', 'defeated', 'tie');--> statement-breakpoint
CREATE TABLE "actor_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"public_key_pem" text NOT NULL,
	"private_key_pem" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "actor_keys_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "analyses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"document_id" uuid NOT NULL,
	"summary" text,
	"key_findings" jsonb,
	"power_map" jsonb,
	"missing_info" jsonb,
	"hidden_assumptions" jsonb,
	"questions_to_ask" jsonb,
	"model" text,
	"prompt_version" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "archive_access_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"archive_record_id" uuid NOT NULL,
	"access_type" "archive_access_type" NOT NULL,
	"accessed_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "archive_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"archive_status" "archive_status" DEFAULT 'pending' NOT NULL,
	"ipfs_cid" text,
	"arweave_tx_id" text,
	"content_hash" text,
	"preserved_at" timestamp,
	"permanence_at" timestamp,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaign_materials" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"material_type" "campaign_material_type" NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"reasoning" text,
	"format" "campaign_material_format" DEFAULT 'json' NOT NULL,
	"metadata" jsonb,
	"status" "campaign_material_status" DEFAULT 'draft' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reporter_id" uuid NOT NULL,
	"target_type" "report_target_type" NOT NULL,
	"target_id" uuid NOT NULL,
	"reason" "report_reason" NOT NULL,
	"description" text,
	"status" "report_status" DEFAULT 'pending' NOT NULL,
	"reviewed_by" uuid,
	"reviewed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "credential_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"credential_type" "credential_type" NOT NULL,
	"weight" integer NOT NULL,
	"source_id" uuid,
	"source_type" "credential_source",
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cross_references" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source_doc_id" uuid NOT NULL,
	"target_doc_id" uuid NOT NULL,
	"relationship_type" "cross_reference_type" NOT NULL,
	"description" text,
	"confidence" real,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "document_chunks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"document_id" uuid NOT NULL,
	"content" text NOT NULL,
	"chunk_index" integer NOT NULL,
	"section_heading" text,
	"embedding" vector(1024),
	"token_count" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "document_versions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"document_id" uuid NOT NULL,
	"version_number" integer NOT NULL,
	"content_hash" text,
	"previous_version_id" uuid,
	"diff_summary" text,
	"change_type" "document_change_type" NOT NULL,
	"detected_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"source_url" text,
	"document_type" "document_type" DEFAULT 'other' NOT NULL,
	"raw_text" text,
	"page_count" integer,
	"word_count" integer,
	"extraction_quality" real,
	"status" "document_status" DEFAULT 'processing' NOT NULL,
	"investigation_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "federal_bills" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"number" text NOT NULL,
	"title_en" text NOT NULL,
	"title_fr" text,
	"short_title_en" text,
	"sponsor_mp_id" uuid,
	"session" text NOT NULL,
	"status_code" text,
	"introduced" date,
	"is_law" boolean,
	"legis_info_url" text,
	"ai_summary" text,
	"ai_summary_prompt_version" text,
	"metadata" jsonb,
	"last_synced_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "federal_mp_ballots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vote_id" uuid NOT NULL,
	"mp_id" uuid NOT NULL,
	"ballot" "mp_ballot" NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "federal_mps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"oparl_slug" text NOT NULL,
	"name" text NOT NULL,
	"party" text NOT NULL,
	"riding_name" text NOT NULL,
	"riding_province" text NOT NULL,
	"email" text,
	"photo_url" text,
	"active" boolean DEFAULT true NOT NULL,
	"metadata" jsonb,
	"last_synced_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "federal_mps_oparl_slug_unique" UNIQUE("oparl_slug")
);
--> statement-breakpoint
CREATE TABLE "federal_votes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session" text NOT NULL,
	"number" integer NOT NULL,
	"date" date NOT NULL,
	"description_en" text NOT NULL,
	"description_fr" text,
	"result" "vote_result" NOT NULL,
	"yea_total" integer NOT NULL,
	"nay_total" integer NOT NULL,
	"paired_total" integer,
	"party_votes" jsonb,
	"bill_id" uuid,
	"ai_explanation" text,
	"ai_explanation_prompt_version" text,
	"last_synced_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"thread_id" uuid NOT NULL,
	"author_id" uuid NOT NULL,
	"parent_id" uuid,
	"content" text NOT NULL,
	"edited_at" timestamp,
	"status" "post_status" DEFAULT 'visible' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_threads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid,
	"author_id" uuid NOT NULL,
	"title" text NOT NULL,
	"jurisdiction_id" uuid,
	"concern_category" text,
	"status" "thread_status" DEFAULT 'open' NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"post_count" integer DEFAULT 0 NOT NULL,
	"last_post_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gadfly_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"document_id" uuid,
	"title" text NOT NULL,
	"complexity_level" integer DEFAULT 1 NOT NULL,
	"question_count" integer DEFAULT 0 NOT NULL,
	"insight_count" integer DEFAULT 0 NOT NULL,
	"mode" "gadfly_mode" DEFAULT 'socratic' NOT NULL,
	"status" "gadfly_status" DEFAULT 'active' NOT NULL,
	"investigation_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gadfly_turns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session_id" uuid NOT NULL,
	"role" "gadfly_role" NOT NULL,
	"content" text NOT NULL,
	"question_type" "gadfly_question_type",
	"turn_index" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "governance_config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" text NOT NULL,
	"value" jsonb NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "governance_config_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "governance_proposals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"author_id" uuid NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"proposal_type" "proposal_type" NOT NULL,
	"status" "proposal_status" DEFAULT 'draft' NOT NULL,
	"voting_opens" timestamp,
	"voting_closes" timestamp,
	"quorum_threshold" real,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "governance_votes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"proposal_id" uuid NOT NULL,
	"voter_id" uuid NOT NULL,
	"choice" "vote_choice" NOT NULL,
	"weight" real NOT NULL,
	"raw_credential_weight" real NOT NULL,
	"voted_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "insight_markers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"turn_id" uuid NOT NULL,
	"session_id" uuid NOT NULL,
	"insight" text NOT NULL,
	"category" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "investigation_outcomes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"outcome_type" "outcome_type" NOT NULL,
	"description" text NOT NULL,
	"outcome_date" date,
	"document_id" uuid,
	"satisfaction" smallint,
	"lessons_learned" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "investigation_players" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"player_id" uuid NOT NULL,
	"role" "investigation_player_role" NOT NULL,
	"context" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "investigation_votes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"vote_id" uuid NOT NULL,
	"relevance_explanation" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "investigations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"concern" text NOT NULL,
	"jurisdiction_id" uuid,
	"jurisdiction_name" text,
	"policy_area" "policy_area",
	"briefing_text" text,
	"briefing_completed_at" timestamp,
	"lens_opened_at" timestamp,
	"lens_context_text" text,
	"lens_completed_at" timestamp,
	"gadfly_seeded_question" text,
	"postal_code" text,
	"federal_mp_id" uuid,
	"campaign_opened_at" timestamp,
	"concern_category" text,
	"environmental_review_type" text,
	"status" "investigation_status" DEFAULT 'active' NOT NULL,
	"preserved_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "issue_tracking" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"event_type" "issue_event_type" NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"event_date" date NOT NULL,
	"reminder_sent" boolean DEFAULT false NOT NULL,
	"status" "issue_status" DEFAULT 'upcoming' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jurisdiction_policies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jurisdiction_id" uuid NOT NULL,
	"policy_area" "policy_area" NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"embedding" vector(1024),
	"source_url" text,
	"implemented_date" date,
	"last_verified_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jurisdictions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"country" text NOT NULL,
	"province" text,
	"municipal_type" "municipal_type" NOT NULL,
	"population" integer,
	"annual_budget" numeric,
	"data_portal_url" text,
	"fippa_body" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lever_actions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"session_id" uuid,
	"document_id" uuid,
	"action_type" "lever_action_type" NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"metadata" jsonb,
	"pdf_url" text,
	"status" "lever_status" DEFAULT 'draft' NOT NULL,
	"investigation_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "magic_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"code" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"used_at" timestamp,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "moderation_actions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"moderator_id" uuid NOT NULL,
	"action_type" "moderation_action_type" NOT NULL,
	"target_type" "report_target_type" NOT NULL,
	"target_id" uuid NOT NULL,
	"reason" text NOT NULL,
	"related_report_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mp_voting_patterns" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mp_id" uuid NOT NULL,
	"session" text NOT NULL,
	"pattern_analysis" text NOT NULL,
	"contradictions" jsonb,
	"prompt_version" text NOT NULL,
	"generated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "parliament_sync_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sync_type" text NOT NULL,
	"session" text,
	"records_fetched" integer,
	"records_upserted" integer,
	"errors" jsonb,
	"duration_ms" integer,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "peer_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"reviewer_id" uuid NOT NULL,
	"factual_accuracy" smallint NOT NULL,
	"source_quality" smallint NOT NULL,
	"missing_context" smallint NOT NULL,
	"strategic_effectiveness" smallint NOT NULL,
	"jurisdictional_accuracy" smallint NOT NULL,
	"summary" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "players" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"player_type" "player_type" NOT NULL,
	"jurisdiction_id" uuid,
	"description" text,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "policy_outcomes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"policy_id" uuid NOT NULL,
	"metric" text NOT NULL,
	"value" text NOT NULL,
	"measure_date" date NOT NULL,
	"source_url" text NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "postal_code_cache" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"postal_code" text NOT NULL,
	"mp_id" uuid,
	"riding_name" text,
	"metadata" jsonb,
	"cached_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "postal_code_cache_postal_code_unique" UNIQUE("postal_code")
);
--> statement-breakpoint
CREATE TABLE "regulatory_processes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid,
	"user_id" uuid NOT NULL,
	"jurisdiction_id" uuid,
	"process_name" text NOT NULL,
	"framework" "regulatory_framework" NOT NULL,
	"project_name" text NOT NULL,
	"proponent_name" text,
	"proponent_player_id" uuid,
	"status" text,
	"comment_period_opens" date,
	"comment_period_closes" date,
	"comment_submission_url" text,
	"registry_url" text,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "remote_followers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"actor_uri" text NOT NULL,
	"actor_inbox" text NOT NULL,
	"shared_inbox" text,
	"display_name" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "scout_sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"jurisdiction_name" text NOT NULL,
	"document_type" text NOT NULL,
	"search_query" text NOT NULL,
	"url" text NOT NULL,
	"title" text,
	"snippet" text,
	"verified" boolean DEFAULT false NOT NULL,
	"cached_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shadow_alerts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"alert_type" "shadow_alert_type" NOT NULL,
	"missing_topic" text NOT NULL,
	"reference_investigation_ids" text[],
	"confidence" real NOT NULL,
	"dismissed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"display_name" text NOT NULL,
	"ap_handle" text,
	"bio" text,
	"avatar_url" text,
	"display_name_changed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_profiles_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "user_profiles_display_name_unique" UNIQUE("display_name"),
	CONSTRAINT "user_profiles_ap_handle_unique" UNIQUE("ap_handle")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_login_at" timestamp,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "actor_keys" ADD CONSTRAINT "actor_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "analyses" ADD CONSTRAINT "analyses_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "archive_access_log" ADD CONSTRAINT "archive_access_log_archive_record_id_archive_records_id_fk" FOREIGN KEY ("archive_record_id") REFERENCES "public"."archive_records"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "archive_records" ADD CONSTRAINT "archive_records_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "archive_records" ADD CONSTRAINT "archive_records_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_materials" ADD CONSTRAINT "campaign_materials_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaign_materials" ADD CONSTRAINT "campaign_materials_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_reports" ADD CONSTRAINT "content_reports_reporter_id_users_id_fk" FOREIGN KEY ("reporter_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_reports" ADD CONSTRAINT "content_reports_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "credential_events" ADD CONSTRAINT "credential_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cross_references" ADD CONSTRAINT "cross_references_source_doc_id_documents_id_fk" FOREIGN KEY ("source_doc_id") REFERENCES "public"."documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cross_references" ADD CONSTRAINT "cross_references_target_doc_id_documents_id_fk" FOREIGN KEY ("target_doc_id") REFERENCES "public"."documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_versions" ADD CONSTRAINT "document_versions_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_versions" ADD CONSTRAINT "document_versions_previous_version_id_document_versions_id_fk" FOREIGN KEY ("previous_version_id") REFERENCES "public"."document_versions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "federal_bills" ADD CONSTRAINT "federal_bills_sponsor_mp_id_federal_mps_id_fk" FOREIGN KEY ("sponsor_mp_id") REFERENCES "public"."federal_mps"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "federal_mp_ballots" ADD CONSTRAINT "federal_mp_ballots_vote_id_federal_votes_id_fk" FOREIGN KEY ("vote_id") REFERENCES "public"."federal_votes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "federal_mp_ballots" ADD CONSTRAINT "federal_mp_ballots_mp_id_federal_mps_id_fk" FOREIGN KEY ("mp_id") REFERENCES "public"."federal_mps"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "federal_votes" ADD CONSTRAINT "federal_votes_bill_id_federal_bills_id_fk" FOREIGN KEY ("bill_id") REFERENCES "public"."federal_bills"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_posts" ADD CONSTRAINT "forum_posts_thread_id_forum_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."forum_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_posts" ADD CONSTRAINT "forum_posts_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_posts" ADD CONSTRAINT "forum_posts_parent_id_forum_posts_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."forum_posts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_threads" ADD CONSTRAINT "forum_threads_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_threads" ADD CONSTRAINT "forum_threads_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_threads" ADD CONSTRAINT "forum_threads_jurisdiction_id_jurisdictions_id_fk" FOREIGN KEY ("jurisdiction_id") REFERENCES "public"."jurisdictions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gadfly_sessions" ADD CONSTRAINT "gadfly_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gadfly_sessions" ADD CONSTRAINT "gadfly_sessions_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gadfly_sessions" ADD CONSTRAINT "gadfly_sessions_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gadfly_turns" ADD CONSTRAINT "gadfly_turns_session_id_gadfly_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."gadfly_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "governance_config" ADD CONSTRAINT "governance_config_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "governance_proposals" ADD CONSTRAINT "governance_proposals_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "governance_votes" ADD CONSTRAINT "governance_votes_proposal_id_governance_proposals_id_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."governance_proposals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "governance_votes" ADD CONSTRAINT "governance_votes_voter_id_users_id_fk" FOREIGN KEY ("voter_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insight_markers" ADD CONSTRAINT "insight_markers_turn_id_gadfly_turns_id_fk" FOREIGN KEY ("turn_id") REFERENCES "public"."gadfly_turns"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "insight_markers" ADD CONSTRAINT "insight_markers_session_id_gadfly_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."gadfly_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_outcomes" ADD CONSTRAINT "investigation_outcomes_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_outcomes" ADD CONSTRAINT "investigation_outcomes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_outcomes" ADD CONSTRAINT "investigation_outcomes_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_players" ADD CONSTRAINT "investigation_players_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_players" ADD CONSTRAINT "investigation_players_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_votes" ADD CONSTRAINT "investigation_votes_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigation_votes" ADD CONSTRAINT "investigation_votes_vote_id_federal_votes_id_fk" FOREIGN KEY ("vote_id") REFERENCES "public"."federal_votes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigations" ADD CONSTRAINT "investigations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigations" ADD CONSTRAINT "investigations_jurisdiction_id_jurisdictions_id_fk" FOREIGN KEY ("jurisdiction_id") REFERENCES "public"."jurisdictions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "investigations" ADD CONSTRAINT "investigations_federal_mp_id_federal_mps_id_fk" FOREIGN KEY ("federal_mp_id") REFERENCES "public"."federal_mps"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_tracking" ADD CONSTRAINT "issue_tracking_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_tracking" ADD CONSTRAINT "issue_tracking_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "jurisdiction_policies" ADD CONSTRAINT "jurisdiction_policies_jurisdiction_id_jurisdictions_id_fk" FOREIGN KEY ("jurisdiction_id") REFERENCES "public"."jurisdictions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lever_actions" ADD CONSTRAINT "lever_actions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lever_actions" ADD CONSTRAINT "lever_actions_session_id_gadfly_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."gadfly_sessions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lever_actions" ADD CONSTRAINT "lever_actions_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lever_actions" ADD CONSTRAINT "lever_actions_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_moderator_id_users_id_fk" FOREIGN KEY ("moderator_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_related_report_id_content_reports_id_fk" FOREIGN KEY ("related_report_id") REFERENCES "public"."content_reports"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mp_voting_patterns" ADD CONSTRAINT "mp_voting_patterns_mp_id_federal_mps_id_fk" FOREIGN KEY ("mp_id") REFERENCES "public"."federal_mps"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "peer_reviews" ADD CONSTRAINT "peer_reviews_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "peer_reviews" ADD CONSTRAINT "peer_reviews_reviewer_id_users_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "players_jurisdiction_id_jurisdictions_id_fk" FOREIGN KEY ("jurisdiction_id") REFERENCES "public"."jurisdictions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "policy_outcomes" ADD CONSTRAINT "policy_outcomes_policy_id_jurisdiction_policies_id_fk" FOREIGN KEY ("policy_id") REFERENCES "public"."jurisdiction_policies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "postal_code_cache" ADD CONSTRAINT "postal_code_cache_mp_id_federal_mps_id_fk" FOREIGN KEY ("mp_id") REFERENCES "public"."federal_mps"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regulatory_processes" ADD CONSTRAINT "regulatory_processes_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regulatory_processes" ADD CONSTRAINT "regulatory_processes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regulatory_processes" ADD CONSTRAINT "regulatory_processes_jurisdiction_id_jurisdictions_id_fk" FOREIGN KEY ("jurisdiction_id") REFERENCES "public"."jurisdictions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regulatory_processes" ADD CONSTRAINT "regulatory_processes_proponent_player_id_players_id_fk" FOREIGN KEY ("proponent_player_id") REFERENCES "public"."players"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remote_followers" ADD CONSTRAINT "remote_followers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadow_alerts" ADD CONSTRAINT "shadow_alerts_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_profiles" ADD CONSTRAINT "user_profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "actor_keys_user_id_idx" ON "actor_keys" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "analyses_document_id_idx" ON "analyses" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "archive_access_log_record_id_idx" ON "archive_access_log" USING btree ("archive_record_id");--> statement-breakpoint
CREATE UNIQUE INDEX "archive_records_investigation_id_unique_idx" ON "archive_records" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "archive_records_user_id_idx" ON "archive_records" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "archive_records_status_idx" ON "archive_records" USING btree ("archive_status");--> statement-breakpoint
CREATE INDEX "campaign_materials_investigation_idx" ON "campaign_materials" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "campaign_materials_type_idx" ON "campaign_materials" USING btree ("material_type");--> statement-breakpoint
CREATE INDEX "content_reports_reporter_id_idx" ON "content_reports" USING btree ("reporter_id");--> statement-breakpoint
CREATE INDEX "content_reports_status_idx" ON "content_reports" USING btree ("status");--> statement-breakpoint
CREATE INDEX "content_reports_target_idx" ON "content_reports" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX "content_reports_created_at_idx" ON "content_reports" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "content_reports_unique_reporter_target_idx" ON "content_reports" USING btree ("reporter_id","target_type","target_id");--> statement-breakpoint
CREATE INDEX "credential_events_user_id_idx" ON "credential_events" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "credential_events_credential_type_idx" ON "credential_events" USING btree ("credential_type");--> statement-breakpoint
CREATE INDEX "credential_events_source_id_idx" ON "credential_events" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX "xref_source_doc_idx" ON "cross_references" USING btree ("source_doc_id");--> statement-breakpoint
CREATE INDEX "xref_target_doc_idx" ON "cross_references" USING btree ("target_doc_id");--> statement-breakpoint
CREATE INDEX "chunks_document_id_idx" ON "document_chunks" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "chunks_chunk_index_idx" ON "document_chunks" USING btree ("document_id","chunk_index");--> statement-breakpoint
CREATE INDEX "document_versions_document_id_idx" ON "document_versions" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "documents_user_id_idx" ON "documents" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "documents_status_idx" ON "documents" USING btree ("status");--> statement-breakpoint
CREATE INDEX "documents_investigation_id_idx" ON "documents" USING btree ("investigation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "federal_bills_session_number_idx" ON "federal_bills" USING btree ("session","number");--> statement-breakpoint
CREATE INDEX "federal_bills_session_idx" ON "federal_bills" USING btree ("session");--> statement-breakpoint
CREATE UNIQUE INDEX "federal_mp_ballots_vote_mp_idx" ON "federal_mp_ballots" USING btree ("vote_id","mp_id");--> statement-breakpoint
CREATE INDEX "federal_mp_ballots_mp_id_idx" ON "federal_mp_ballots" USING btree ("mp_id");--> statement-breakpoint
CREATE INDEX "federal_mps_riding_province_idx" ON "federal_mps" USING btree ("riding_province");--> statement-breakpoint
CREATE INDEX "federal_mps_party_idx" ON "federal_mps" USING btree ("party");--> statement-breakpoint
CREATE INDEX "federal_mps_active_idx" ON "federal_mps" USING btree ("active");--> statement-breakpoint
CREATE UNIQUE INDEX "federal_votes_session_number_idx" ON "federal_votes" USING btree ("session","number");--> statement-breakpoint
CREATE INDEX "federal_votes_date_idx" ON "federal_votes" USING btree ("date");--> statement-breakpoint
CREATE INDEX "federal_votes_bill_id_idx" ON "federal_votes" USING btree ("bill_id");--> statement-breakpoint
CREATE INDEX "forum_posts_thread_id_idx" ON "forum_posts" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "forum_posts_author_id_idx" ON "forum_posts" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "forum_posts_parent_id_idx" ON "forum_posts" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "forum_threads_author_id_idx" ON "forum_threads" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "forum_threads_investigation_id_idx" ON "forum_threads" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "forum_threads_status_idx" ON "forum_threads" USING btree ("status");--> statement-breakpoint
CREATE INDEX "forum_threads_jurisdiction_id_idx" ON "forum_threads" USING btree ("jurisdiction_id");--> statement-breakpoint
CREATE INDEX "gadfly_sessions_user_id_idx" ON "gadfly_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "gadfly_sessions_status_idx" ON "gadfly_sessions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "gadfly_sessions_investigation_id_idx" ON "gadfly_sessions" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "gadfly_turns_session_id_idx" ON "gadfly_turns" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "gadfly_turns_turn_index_idx" ON "gadfly_turns" USING btree ("session_id","turn_index");--> statement-breakpoint
CREATE INDEX "proposals_author_id_idx" ON "governance_proposals" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX "proposals_status_idx" ON "governance_proposals" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "votes_proposal_voter_unique_idx" ON "governance_votes" USING btree ("proposal_id","voter_id");--> statement-breakpoint
CREATE INDEX "votes_proposal_id_idx" ON "governance_votes" USING btree ("proposal_id");--> statement-breakpoint
CREATE INDEX "insight_markers_session_id_idx" ON "insight_markers" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "insight_markers_turn_id_idx" ON "insight_markers" USING btree ("turn_id");--> statement-breakpoint
CREATE INDEX "inv_outcomes_investigation_idx" ON "investigation_outcomes" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "inv_outcomes_type_idx" ON "investigation_outcomes" USING btree ("outcome_type");--> statement-breakpoint
CREATE INDEX "inv_players_investigation_idx" ON "investigation_players" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "inv_players_player_idx" ON "investigation_players" USING btree ("player_id");--> statement-breakpoint
CREATE UNIQUE INDEX "inv_players_unique_role_idx" ON "investigation_players" USING btree ("investigation_id","player_id","role");--> statement-breakpoint
CREATE UNIQUE INDEX "investigation_votes_inv_vote_idx" ON "investigation_votes" USING btree ("investigation_id","vote_id");--> statement-breakpoint
CREATE INDEX "investigation_votes_investigation_idx" ON "investigation_votes" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "investigations_user_id_idx" ON "investigations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "investigations_status_idx" ON "investigations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "investigations_created_at_idx" ON "investigations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "issue_tracking_investigation_idx" ON "issue_tracking" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "issue_tracking_event_date_idx" ON "issue_tracking" USING btree ("event_date");--> statement-breakpoint
CREATE INDEX "issue_tracking_status_idx" ON "issue_tracking" USING btree ("status");--> statement-breakpoint
CREATE INDEX "jp_jurisdiction_id_idx" ON "jurisdiction_policies" USING btree ("jurisdiction_id");--> statement-breakpoint
CREATE INDEX "jp_policy_area_idx" ON "jurisdiction_policies" USING btree ("policy_area");--> statement-breakpoint
CREATE INDEX "jurisdictions_country_idx" ON "jurisdictions" USING btree ("country");--> statement-breakpoint
CREATE INDEX "jurisdictions_province_idx" ON "jurisdictions" USING btree ("province");--> statement-breakpoint
CREATE INDEX "lever_actions_user_id_idx" ON "lever_actions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "lever_actions_status_idx" ON "lever_actions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "lever_actions_investigation_id_idx" ON "lever_actions" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "magic_codes_email_idx" ON "magic_codes" USING btree ("email");--> statement-breakpoint
CREATE INDEX "moderation_actions_moderator_id_idx" ON "moderation_actions" USING btree ("moderator_id");--> statement-breakpoint
CREATE INDEX "moderation_actions_target_idx" ON "moderation_actions" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX "moderation_actions_related_report_idx" ON "moderation_actions" USING btree ("related_report_id");--> statement-breakpoint
CREATE INDEX "moderation_actions_created_at_idx" ON "moderation_actions" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "mp_voting_patterns_mp_session_idx" ON "mp_voting_patterns" USING btree ("mp_id","session");--> statement-breakpoint
CREATE INDEX "parliament_sync_log_type_idx" ON "parliament_sync_log" USING btree ("sync_type");--> statement-breakpoint
CREATE INDEX "parliament_sync_log_started_at_idx" ON "parliament_sync_log" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "peer_reviews_investigation_id_idx" ON "peer_reviews" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "peer_reviews_reviewer_id_idx" ON "peer_reviews" USING btree ("reviewer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "peer_reviews_unique_idx" ON "peer_reviews" USING btree ("investigation_id","reviewer_id");--> statement-breakpoint
CREATE INDEX "players_name_idx" ON "players" USING btree ("name");--> statement-breakpoint
CREATE INDEX "players_type_idx" ON "players" USING btree ("player_type");--> statement-breakpoint
CREATE INDEX "policy_outcomes_policy_id_idx" ON "policy_outcomes" USING btree ("policy_id");--> statement-breakpoint
CREATE INDEX "policy_outcomes_measure_date_idx" ON "policy_outcomes" USING btree ("measure_date");--> statement-breakpoint
CREATE INDEX "postal_code_cache_postal_code_idx" ON "postal_code_cache" USING btree ("postal_code");--> statement-breakpoint
CREATE INDEX "reg_processes_investigation_idx" ON "regulatory_processes" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "reg_processes_user_id_idx" ON "regulatory_processes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "reg_processes_framework_idx" ON "regulatory_processes" USING btree ("framework");--> statement-breakpoint
CREATE INDEX "reg_processes_comment_closes_idx" ON "regulatory_processes" USING btree ("comment_period_closes");--> statement-breakpoint
CREATE INDEX "remote_followers_user_id_idx" ON "remote_followers" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "remote_followers_unique_idx" ON "remote_followers" USING btree ("user_id","actor_uri");--> statement-breakpoint
CREATE INDEX "scout_sources_jurisdiction_idx" ON "scout_sources" USING btree ("jurisdiction_name");--> statement-breakpoint
CREATE INDEX "scout_sources_doc_type_idx" ON "scout_sources" USING btree ("document_type");--> statement-breakpoint
CREATE INDEX "shadow_alerts_investigation_id_idx" ON "shadow_alerts" USING btree ("investigation_id");--> statement-breakpoint
CREATE INDEX "user_profiles_user_id_idx" ON "user_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_profiles_display_name_idx" ON "user_profiles" USING btree ("display_name");--> statement-breakpoint
CREATE INDEX "user_profiles_ap_handle_idx" ON "user_profiles" USING btree ("ap_handle");