import { NextRequest } from 'next/server'
import { getDb } from '@/lib/db'
import { leverActions } from '@/lib/db/schema'
import { eq, and } from 'drizzle-orm'

const ACTION_TYPE_LABELS: Record<string, string> = {
  fippa_request: 'fippa-request',
  public_comment: 'public-comment',
  policy_brief: 'policy-brief',
}

const ACTION_TYPE_DISPLAY: Record<string, string> = {
  fippa_request: 'FOI Request (FIPPA)',
  public_comment: 'Public Comment',
  policy_brief: 'Policy Brief',
  legal_template: 'Legal Template',
  media_spec: 'Media Specification',
  talking_points: 'Talking Points',
  coalition_template: 'Coalition Template',
  mp_letter: 'Letter to MP',
}

/**
 * POST /api/lever/export
 * Returns the action content as a downloadable file.
 *
 * Body: { actionId: string, format?: 'txt' | 'md' }
 * - txt (default): plain text
 * - md: Markdown with YAML frontmatter and section headers
 */
export async function POST(request: NextRequest) {
  const userId = request.headers.get('x-user-id')
  if (!userId) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  let body: { actionId: string; format?: 'txt' | 'md' }
  try {
    body = await request.json()
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const { actionId, format = 'txt' } = body
  if (!actionId) {
    return new Response(JSON.stringify({ error: 'actionId is required' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  if (format !== 'txt' && format !== 'md') {
    return new Response(JSON.stringify({ error: 'format must be "txt" or "md"' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const db = getDb()

  const [action] = await db
    .select({
      id: leverActions.id,
      title: leverActions.title,
      actionType: leverActions.actionType,
      content: leverActions.content,
      status: leverActions.status,
      metadata: leverActions.metadata,
      createdAt: leverActions.createdAt,
    })
    .from(leverActions)
    .where(and(eq(leverActions.id, actionId), eq(leverActions.userId, userId)))
    .limit(1)

  if (!action) {
    return new Response(JSON.stringify({ error: 'Action not found' }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  if (!action.content) {
    return new Response(JSON.stringify({ error: 'Action has no content to export' }), {
      status: 409,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const date = new Date(action.createdAt).toISOString().slice(0, 10)
  const typeSlug = ACTION_TYPE_LABELS[action.actionType] ?? 'action'

  if (format === 'md') {
    const metadata = (action.metadata ?? {}) as Record<string, unknown>
    const publicBody = (metadata.publicBody as string) ?? ''
    const typeDisplay = ACTION_TYPE_DISPLAY[action.actionType] ?? action.actionType

    // Build YAML frontmatter — JSON.stringify produces valid YAML double-quoted strings
    const frontmatter = [
      '---',
      `title: ${JSON.stringify(action.title)}`,
      `type: ${JSON.stringify(typeDisplay)}`,
      `date: ${JSON.stringify(date)}`,
      `status: ${JSON.stringify(action.status)}`,
    ]
    if (publicBody) {
      frontmatter.push(`public_body: ${JSON.stringify(publicBody)}`)
    }
    frontmatter.push('---')

    // Wrap content with section headers based on action type
    const body = formatContentAsMarkdown(action.actionType, action.content, action.title)

    const mdContent = frontmatter.join('\n') + '\n\n' + body + '\n\n---\n\n*Generated by The Republic -- ' + date + '*\n'
    const filename = `${typeSlug}-${date}.md`

    return new Response(mdContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  }

  // Default: plain text
  const filename = `${typeSlug}-${date}.txt`
  return new Response(action.content, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}

/**
 * Add Markdown section headers to the raw text content based on action type.
 */
function formatContentAsMarkdown(
  actionType: string,
  content: string,
  title: string
): string {
  const lines: string[] = []

  lines.push(`# ${title}`)
  lines.push('')

  switch (actionType) {
    case 'fippa_request':
      lines.push('## Freedom of Information Request')
      lines.push('')
      lines.push(content)
      break
    case 'public_comment':
      lines.push('## Public Comment Submission')
      lines.push('')
      lines.push(content)
      break
    case 'policy_brief':
      lines.push('## Policy Brief')
      lines.push('')
      lines.push(content)
      break
    default:
      lines.push(content)
      break
  }

  return lines.join('\n')
}
